services:
  supabase-grafana:
    build: ./
    ports:
      - 3000:8080
    environment:
      SUPABASE_ACCESS_TOKEN: ${SUPABASE_ACCESS_TOKEN}
      SUPABASE_ORGANIZATION_ID: ${SUPABASE_ORGANIZATION_ID}
      SUPABASE_PROJECT_REF: ${SUPABASE_PROJECT_REF}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      PASSWORD_PROTECTED: ${PASSWORD_PROTECTED}
      GRAFANA_PASSWORD: ${GRAFANA_PASSWORD}

      # Azure PostgreSQL Configuration
      AZURE_POSTGRES_ENABLED: ${AZURE_POSTGRES_ENABLED:-false}
      AZURE_POSTGRES_NAME: ${AZURE_POSTGRES_NAME}
      AZURE_POSTGRES_HOST: ${AZURE_POSTGRES_HOST}
      AZURE_POSTGRES_PORT: ${AZURE_POSTGRES_PORT:-5432}
      AZURE_POSTGRES_USER: ${AZURE_POSTGRES_USER}
      AZURE_POSTGRES_PASSWORD: ${AZURE_POSTGRES_PASSWORD}

      POSTGRES_PRIMARY_ENABLED: ${POSTGRES_PRIMARY_ENABLED}
      POSTGRES_PRIMARY_NAME: ${POSTGRES_PRIMARY_NAME}
      POSTGRES_PRIMARY_HOST: ${POSTGRES_PRIMARY_HOST}
      POSTGRES_PRIMARY_PORT: ${POSTGRES_PRIMARY_PORT:-5432}
      POSTGRES_PRIMARY_USER: ${POSTGRES_PRIMARY_USER}
      POSTGRES_PRIMARY_PASSWORD: ${POSTGRES_PRIMARY_PASSWORD}

      POSTGRES_READ_ENABLED: ${POSTGRES_READ_ENABLED}
      POSTGRES_READ_NAME: ${POSTGRES_READ_NAME}
      POSTGRES_READ_HOST: ${POSTGRES_READ_HOST}
      POSTGRES_READ_PORT: ${POSTGRES_READ_PORT}
      POSTGRES_READ_USER: ${POSTGRES_READ_USER}
      POSTGRES_READ_PASSWORD: ${POSTGRES_READ_PASSWORD}
    volumes:
      - ./data:/data
